# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: mithileshk123

# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-python-http-api-project

# Specify the Serverless framework version
frameworkVersion: '4'

# Provider configuration
provider:
  name: aws
  runtime: python3.12
  region: us-west-2

# Function definitions
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
  bye:
    handler: handler.bye
    events:
      - httpApi:
          path: /bye
          method: get

~                                                                                          
~                                                                                          
~                                                                                          
~              
